# Generated by Django 5.0.4 on 2024-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_albom_cover_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='cover',
            field=models.URLField(),
        ),
    ]
