# Generated by Django 5.0.3 on 2024-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_songs_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='cover',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
